/* ════════════════════════════════════════════════════════════════
   IMPRESSUM und DATENSCHUTZERKLÄRUNG
   Texte 1:1 aus offiziellem Auftraggeber-Material übernommen
   ════════════════════════════════════════════════════════════════ */

window._IMPRESSUM_HTML =
'<h3>Impressum</h3>'
+ '<p><strong>GEMEINSCHAFTSINITIATIVE \u201CWIR WESTERW\u00C4LDER\u201D</strong><br>'
+ 'Aktiv zwischen Rhein und Sieg</p>'
+ '<p>Wir Westerw\u00E4lder gA\u00F6R<br>'
+ 'K\u00F6nigsberger Str. 40<br>'
+ '56269 Dierdorf</p>'

+ '<h3>Kontakt</h3>'
+ '<p>Telefon: 02689 95929-40<br>'
+ 'Telefax: 02689 95929-49<br>'
+ 'E-Mail: <a href="mailto:info@wir-westerwaelder.de">info@wir-westerwaelder.de</a></p>'

+ '<p>Vorstand: Sandra K\u00F6ster<br>'
+ 'Vorsitzender des Verwaltungsrates: Landrat Achim Hallerbach</p>'

+ '<p>Die Gemeinschaftsinitiative \u201CWir Westerw\u00E4lder\u201D wird getragen durch die Landkreise Altenkirchen, Neuwied und Westerwaldkreis. Die Landkreise sind K\u00F6rperschaften des \u00F6ffentlichen Rechts. Sie werden durch den jeweiligen Landrat vertreten.</p>'

+ '<p><strong>Kreisverwaltung Altenkirchen</strong><br>'
+ 'Vertreten durch:<br>'
+ 'Landrat Dr. Peter Enders<br>'
+ 'Parkstra\u00DFe 1<br>'
+ '57610 Altenkirchen<br>'
+ 'Telefon: 02681 81-0<br>'
+ 'Telefax: 02681 81-2000<br>'
+ 'E-Mail: <a href="mailto:post@kreis-ak.de">post@kreis-ak.de</a></p>'

+ '<p><strong>Kreisverwaltung Neuwied</strong><br>'
+ 'Vertreten durch:<br>'
+ 'Landrat Achim Hallerbach<br>'
+ 'Wilhelm-Leuschner-Stra\u00DFe 9<br>'
+ 'D-56564 Neuwied<br>'
+ 'Telefon: 02631 803-0 (Zentrale)<br>'
+ 'Telefax: 02631 803-93-222<br>'
+ 'E-Mail: <a href="mailto:poststelle@kreis-neuwied.de">poststelle@kreis-neuwied.de</a></p>'

+ '<p><strong>Kreisverwaltung des Westerwaldkreises</strong><br>'
+ 'Vertreten durch:<br>'
+ 'Landrat Achim Schwickert<br>'
+ 'Peter-Altmeier-Platz 1<br>'
+ '56410 Montabaur<br>'
+ 'Telefon: 02602 124-0<br>'
+ 'Telefax: 02602 124-238<br>'
+ 'E-Mail: <a href="mailto:kreisverwaltung@westerwaldkreis.de">kreisverwaltung@westerwaldkreis.de</a></p>'

+ '<h3>Inhaltliche Verantwortung</h3>'
+ '<p>Sandra K\u00F6ster<br>'
+ 'Wir Westerw\u00E4lder gA\u00F6R<br>'
+ 'K\u00F6nigsberger Stra\u00DFe 40, 56269 Dierdorf<br>'
+ 'Telefon 02689-95929-40</p>'

+ '<h3>Konzeption, Design, Entwicklung &amp; Programmierung</h3>'
+ '<p>PAGE &amp; PAPER \u2013 Agentur f\u00FCr Kommunikation GmbH &amp; Co. KG<br>'
+ 'Barrwiese 3<br>'
+ '57627 Hachenburg</p>'

+ '<p><strong>Weitere Kan\u00E4le der Wir Westerw\u00E4lder gA\u00F6R</strong></p>'
+ '<ul>'
+ '<li>Website: <a href="https://www.wir-westerwaelder.de" target="_blank" rel="noopener">www.wir-westerwaelder.de</a></li>'
+ '<li>Spotify</li>'
+ '<li>Apple Podcast</li>'
+ '<li>LinkedIn</li>'
+ '<li>YouTube</li>'
+ '<li>Instagram</li>'
+ '<li>Facebook</li>'
+ '</ul>'

+ '<h3>Bildnachweis</h3>'
+ '<p>Dominik Ketz Fotografie, <a href="https://www.dominikketz.de" target="_blank" rel="noopener">www.dominikketz.de</a><br>'
+ 'Matthias Ketz Photographie, <a href="https://www.foto-ketz.de" target="_blank" rel="noopener">www.foto-ketz.de</a><br>'
+ 'Martin Fandler, foto-fandler.de<br>'
+ 'Tourist-Information Montabaur, kmaas@montabaur.de<br>'
+ 'Tourist-Information Rengsdorf, tourist@rengsdorf.de<br>'
+ 'Hotel Heinz GmbH, info@hotel-heinz.de<br>'
+ 'Rheinland-Pfalz Tourismus GmbH, info@gastlandschaften.de<br>'
+ 'J\u00F6rg Hohenadl; Naturgenuss Rhein-Westerwald, <a href="https://www.naturgenuss-partner.de" target="_blank" rel="noopener">www.naturgenuss-partner.de</a><br>'
+ 'Regionale Partner aus dem Einkaufsf\u00FChrer Westerwald</p>'

+ '<h3>Bildnachweise</h3>'
+ '<p>Die folgenden Bilder wurden verwendet und stammen von den genannten Quellen:</p>'
+ '<p><strong>Adobe Stock</strong></p>'
+ '<ul>'
+ '<li>AdobeStock_144420188.ai</li>'
+ '<li>AdobeStock_244784231.jpeg</li>'
+ '<li>AdobeStock_352139863.jpeg</li>'
+ '<li>AdobeStock_354792162.jpeg</li>'
+ '<li>AdobeStock_397095086.ai</li>'
+ '<li>AdobeStock_442937999.jpeg</li>'
+ '<li>AdobeStock_553143458.ai</li>'
+ '<li>AdobeStock_576871114.ai</li>'
+ '<li>AdobeStock_576871114.jpeg</li>'
+ '<li>AdobeStock_807136369.jpeg</li>'
+ '<li>AdobeStock_825087493.jpeg</li>'
+ '<li>AdobeStock_890986439.jpeg</li>'
+ '<li>AdobeStock_1007148027.jpeg</li>'
+ '<li>AdobeStock_1012018936.jpeg</li>'
+ '<li>AdobeStock_1024593601.jpeg</li>'
+ '<li>AdobeStock_1037823821.jpeg</li>'
+ '<li>AdobeStock_1070253592.jpeg</li>'
+ '<li>AdobeStock_1088483877.jpeg</li>'
+ '<li>AdobeStock_1136711510.jpeg</li>'
+ '<li>AdobeStock_1200051178.jpeg</li>'
+ '<li>AdobeStock_1233686142.jpeg</li>'
+ '<li>AdobeStock_1251914079.jpeg</li>'
+ '</ul>'
+ '<p><strong>iStock</strong></p>'
+ '<ul>'
+ '<li>iStock-683962670.jpg</li>'
+ '<li>iStock-1159783574.eps</li>'
+ '<li>iStock-1176632037.jpg</li>'
+ '<li>iStock-1316989941.eps</li>'
+ '<li>iStock-1318686980.eps</li>'
+ '<li>iStock-2174600729.jpg</li>'
+ '<li>iStock-2191560255.jpg</li>'
+ '</ul>'
+ '<p>Martina Haas, <a href="https://www.haas-ideen.com" target="_blank" rel="noopener">www.haas-ideen.com</a></p>'

+ '<h3>HAFTUNGSAUSSCHLUSS (DISCLAIMER)</h3>'
+ '<p><strong>HAFTUNG F\u00DCR INHALTE</strong></p>'
+ '<p>Als Diensteanbieter sind wir gem\u00E4\u00DF \u00A7 7 Abs.1 TMG f\u00FCr eigene Inhalte auf diesen Seiten nach den allgemeinen Gesetzen verantwortlich. Nach \u00A7\u00A7 8 bis 10 TMG sind wir als Diensteanbieter jedoch nicht verpflichtet, \u00FCbermittelte oder gespeicherte fremde Informationen zu \u00FCberwachen oder nach Umst\u00E4nden zu forschen, die auf eine rechtswidrige T\u00E4tigkeit hinweisen. Verpflichtungen zur Entfernung oder Sperrung der Nutzung von Informationen nach den allgemeinen Gesetzen bleiben hiervon unber\u00FChrt. Eine diesbez\u00FCgliche Haftung ist jedoch erst ab dem Zeitpunkt der Kenntnis einer konkreten Rechtsverletzung m\u00F6glich. Bei Bekanntwerden von entsprechenden Rechtsverletzungen werden wir diese Inhalte umgehend entfernen.</p>'

+ '<p><strong>HAFTUNG F\u00DCR LINKS</strong></p>'
+ '<p>Unser Angebot enth\u00E4lt Links zu externen Webseiten Dritter, auf deren Inhalte wir keinen Einfluss haben. Deshalb k\u00F6nnen wir f\u00FCr diese fremden Inhalte auch keine Gew\u00E4hr \u00FCbernehmen. F\u00FCr die Inhalte der verlinkten Seiten ist stets der jeweilige Anbieter oder Betreiber der Seiten verantwortlich. Die verlinkten Seiten wurden zum Zeitpunkt der Verlinkung auf m\u00F6gliche Rechtsverst\u00F6\u00DFe \u00FCberpr\u00FCft. Rechtswidrige Inhalte waren zum Zeitpunkt der Verlinkung nicht erkennbar. Eine permanente inhaltliche Kontrolle der verlinkten Seiten ist jedoch ohne konkrete Anhaltspunkte einer Rechtsverletzung nicht zumutbar. Bei Bekanntwerden von Rechtsverletzungen werden wir derartige Links umgehend entfernen.</p>'

+ '<p><strong>URHEBERRECHT</strong></p>'
+ '<p>Die durch die Seitenbetreiber erstellten Inhalte und Werke auf diesen Seiten unterliegen dem deutschen Urheberrecht. Die Vervielf\u00E4ltigung, Bearbeitung, Verbreitung und jede Art der Verwertung au\u00DFerhalb der Grenzen des Urheberrechtes bed\u00FCrfen der schriftlichen Zustimmung des jeweiligen Autors bzw. Erstellers. Downloads und Kopien dieser Seite sind nur f\u00FCr den privaten, nicht kommerziellen Gebrauch gestattet. Soweit die Inhalte auf dieser Seite nicht vom Betreiber erstellt wurden, werden die Urheberrechte Dritter beachtet. Insbesondere werden Inhalte Dritter als solche gekennzeichnet. Sollten Sie trotzdem auf eine Urheberrechtsverletzung aufmerksam werden, bitten wir um einen entsprechenden Hinweis. Bei Bekanntwerden von Rechtsverletzungen werden wir derartige Inhalte umgehend entfernen.</p>'

+ '<h3>EU-Streitschlichtung</h3>'
+ '<p>Die Europ\u00E4ische Kommission stellt eine Plattform zur Online-Streitbeilegung (OS) bereit: '
+ '<a href="https://ec.europa.eu/consumers/odr/" target="_blank" rel="noopener">https://ec.europa.eu/consumers/odr/</a>.<br>'
+ 'Unsere E-Mail-Adresse finden Sie oben im Impressum.</p>'

+ '<h3>Verbraucherstreitbeilegung / Universalschlichtungsstelle</h3>'
+ '<p>Wir sind nicht bereit oder verpflichtet, an Streitbeilegungsverfahren vor einer Verbraucherschlichtungsstelle teilzunehmen.</p>';


window._DATENSCHUTZ_HTML =
'<h3>Datenschutzerkl\u00E4rung</h3>'

+ '<h3>1. Datenschutz auf einen Blick</h3>'
+ '<p><strong>Allgemeine Hinweise</strong></p>'
+ '<p>Die folgenden Hinweise geben einen einfachen \u00DCberblick dar\u00FCber, was mit Ihren personenbezogenen Daten passiert, wenn Sie diese Website besuchen. Personenbezogene Daten sind alle Daten, mit denen Sie pers\u00F6nlich identifiziert werden k\u00F6nnen. Ausf\u00FChrliche Informationen zum Thema Datenschutz entnehmen Sie unserer unter diesem Text aufgef\u00FChrten Datenschutzerkl\u00E4rung.</p>'

+ '<p><strong>Datenerfassung auf dieser Website</strong></p>'

+ '<p><strong>Wer ist verantwortlich f\u00FCr die Datenerfassung auf dieser Website?</strong></p>'
+ '<p>Die Datenverarbeitung auf dieser Website erfolgt durch den Websitebetreiber. Dessen Kontaktdaten k\u00F6nnen Sie dem Abschnitt \u201EHinweis zur Verantwortlichen Stelle\u201C in dieser Datenschutzerkl\u00E4rung entnehmen.</p>'

+ '<p><strong>Wie erfassen wir Ihre Daten?</strong></p>'
+ '<p>Ihre Daten werden zum einen dadurch erhoben, dass Sie uns diese mitteilen. Hierbei kann es sich z. B. um Daten handeln, die Sie in ein Kontaktformular eingeben.</p>'
+ '<p>Andere Daten werden automatisch oder nach Ihrer Einwilligung beim Besuch der Website durch unsere IT-Systeme erfasst. Das sind vor allem technische Daten (z. B. Internetbrowser, Betriebssystem oder Uhrzeit des Seitenaufrufs). Die Erfassung dieser Daten erfolgt automatisch, sobald Sie diese Website betreten.</p>'

+ '<p><strong>Wof\u00FCr nutzen wir Ihre Daten?</strong></p>'
+ '<p>Ein Teil der Daten wird erhoben, um eine fehlerfreie Bereitstellung der Website zu gew\u00E4hrleisten. Andere Daten k\u00F6nnen zur Analyse Ihres Nutzerverhaltens verwendet werden. Sofern \u00FCber die Website Vertr\u00E4ge geschlossen oder angebahnt werden k\u00F6nnen, werden die \u00FCbermittelten Daten auch f\u00FCr Vertragsangebote, Bestellungen oder sonstige Auftragsanfragen verarbeitet.</p>'

+ '<p><strong>Welche Rechte haben Sie bez\u00FCglich Ihrer Daten?</strong></p>'
+ '<p>Sie haben jederzeit das Recht, unentgeltlich Auskunft \u00FCber Herkunft, Empf\u00E4nger und Zweck Ihrer gespeicherten personenbezogenen Daten zu erhalten. Sie haben au\u00DFerdem ein Recht, die Berichtigung oder L\u00F6schung dieser Daten zu verlangen. Wenn Sie eine Einwilligung zur Datenverarbeitung erteilt haben, k\u00F6nnen Sie diese Einwilligung jederzeit f\u00FCr die Zukunft widerrufen. Au\u00DFerdem haben Sie das Recht, unter bestimmten Umst\u00E4nden die Einschr\u00E4nkung der Verarbeitung Ihrer personenbezogenen Daten zu verlangen. Des Weiteren steht Ihnen ein Beschwerderecht bei der zust\u00E4ndigen Aufsichtsbeh\u00F6rde zu.</p>'
+ '<p>Hierzu sowie zu weiteren Fragen zum Thema Datenschutz k\u00F6nnen Sie sich jederzeit an uns wenden.</p>'

+ '<h3>2. Hosting</h3>'
+ '<p>Wir hosten die Inhalte unserer Website bei folgendem Anbieter:</p>'
+ '<p><strong>Hetzner</strong></p>'
+ '<p>Anbieter ist die Hetzner Online GmbH, Industriestr. 25, 91710 Gunzenhausen (nachfolgend Hetzner).</p>'
+ '<p>Details entnehmen Sie der Datenschutzerkl\u00E4rung von Hetzner: <a href="https://www.hetzner.com/de/legal/privacy-policy/" target="_blank" rel="noopener">https://www.hetzner.com/de/legal/privacy-policy/</a>.</p>'
+ '<p>Die Verwendung von Hetzner erfolgt auf Grundlage von Art. 6 Abs. 1 lit. f DSGVO. Wir haben ein berechtigtes Interesse an einer m\u00F6glichst zuverl\u00E4ssigen Darstellung unserer Website. Sofern eine entsprechende Einwilligung abgefragt wurde, erfolgt die Verarbeitung ausschlie\u00DFlich auf Grundlage von Art. 6 Abs. 1 lit. a DSGVO und \u00A7 25 Abs. 1 TDDDG, soweit die Einwilligung die Speicherung von Cookies oder den Zugriff auf Informationen im Endger\u00E4t des Nutzers (z. B. Device-Fingerprinting) im Sinne des TDDDG umfasst. Die Einwilligung ist jederzeit widerrufbar.</p>'
+ '<p><strong>Auftragsverarbeitung</strong></p>'
+ '<p>Wir haben einen Vertrag \u00FCber Auftragsverarbeitung (AVV) zur Nutzung des oben genannten Dienstes geschlossen. Hierbei handelt es sich um einen datenschutzrechtlich vorgeschriebenen Vertrag, der gew\u00E4hrleistet, dass dieser die personenbezogenen Daten unserer Websitebesucher nur nach unseren Weisungen und unter Einhaltung der DSGVO verarbeitet.</p>'

+ '<h3>3. Allgemeine Hinweise und Pflichtinformationen</h3>'
+ '<p><strong>Datenschutz</strong></p>'
+ '<p>Die Betreiber dieser Seiten nehmen den Schutz Ihrer pers\u00F6nlichen Daten sehr ernst. Wir behandeln Ihre personenbezogenen Daten vertraulich und entsprechend den gesetzlichen Datenschutzvorschriften sowie dieser Datenschutzerkl\u00E4rung.</p>'
+ '<p>Wenn Sie diese Website benutzen, werden verschiedene personenbezogene Daten erhoben. Personenbezogene Daten sind Daten, mit denen Sie pers\u00F6nlich identifiziert werden k\u00F6nnen. Die vorliegende Datenschutzerkl\u00E4rung erl\u00E4utert, welche Daten wir erheben und wof\u00FCr wir sie nutzen. Sie erl\u00E4utert auch, wie und zu welchem Zweck das geschieht.</p>'
+ '<p>Wir weisen darauf hin, dass die Daten\u00FCbertragung im Internet (z. B. bei der Kommunikation per E-Mail) Sicherheitsl\u00FCcken aufweisen kann. Ein l\u00FCckenloser Schutz der Daten vor dem Zugriff durch Dritte ist nicht m\u00F6glich.</p>'

+ '<p><strong>Hinweis zur verantwortlichen Stelle</strong></p>'
+ '<p>Die verantwortliche Stelle f\u00FCr die Datenverarbeitung auf dieser Website ist:</p>'
+ '<p><strong>Kreisverwaltung Altenkirchen</strong><br>'
+ 'Vertreten durch:<br>'
+ 'Landrat Michael Lieber<br>'
+ 'Parkstra\u00DFe 1<br>'
+ '57610 Altenkirchen<br>'
+ 'Telefon: 02681 81-0<br>'
+ 'Telefax: 02681 812000<br>'
+ 'E-Mail: <a href="mailto:post@kreis-ak.de">post@kreis-ak.de</a></p>'
+ '<p><strong>Kreisverwaltung Neuwied</strong><br>'
+ 'Vertreten durch:<br>'
+ 'Landrat Achim Hallerbach<br>'
+ 'Wilhelm-Leuschner-Stra\u00DFe 9<br>'
+ 'D-56564 Neuwied<br>'
+ 'Telefon: 02631 803-0 (Zentrale)<br>'
+ 'Telefax: 02631 803-93-222<br>'
+ 'E-Mail: <a href="mailto:poststelle@kreis-neuwied.de">poststelle@kreis-neuwied.de</a></p>'
+ '<p><strong>Kreisverwaltung des Westerwaldkreises</strong><br>'
+ 'Vertreten durch:<br>'
+ 'Landrat Achim Schwickert<br>'
+ 'Peter-Altmeier-Platz 1<br>'
+ '56410 Montabaur<br>'
+ 'Telefon: 02602 124-0<br>'
+ 'Telefax: 02602 124-238<br>'
+ 'E-Mail: <a href="mailto:kreisverwaltung@westerwaldkreis.de">kreisverwaltung@westerwaldkreis.de</a></p>'
+ '<p>Verantwortliche Stelle ist die nat\u00FCrliche oder juristische Person, die allein oder gemeinsam mit anderen \u00FCber die Zwecke und Mittel der Verarbeitung von personenbezogenen Daten (z. B. Namen, E-Mail-Adressen o. \u00C4.) entscheidet.</p>'

+ '<p><strong>Speicherdauer</strong></p>'
+ '<p>Soweit innerhalb dieser Datenschutzerkl\u00E4rung keine speziellere Speicherdauer genannt wurde, verbleiben Ihre personenbezogenen Daten bei uns, bis der Zweck f\u00FCr die Datenverarbeitung entf\u00E4llt. Wenn Sie ein berechtigtes L\u00F6schersuchen geltend machen oder eine Einwilligung zur Datenverarbeitung widerrufen, werden Ihre Daten gel\u00F6scht, sofern wir keine anderen rechtlich zul\u00E4ssigen Gr\u00FCnde f\u00FCr die Speicherung Ihrer personenbezogenen Daten haben (z. B. steuer- oder handelsrechtliche Aufbewahrungsfristen); im letztgenannten Fall erfolgt die L\u00F6schung nach Fortfall dieser Gr\u00FCnde.</p>'

+ '<p><strong>Allgemeine Hinweise zu den Rechtsgrundlagen der Datenverarbeitung auf dieser Website</strong></p>'
+ '<p>Sofern Sie in die Datenverarbeitung eingewilligt haben, verarbeiten wir Ihre personenbezogenen Daten auf Grundlage von Art. 6 Abs. 1 lit. a DSGVO bzw. Art. 9 Abs. 2 lit. a DSGVO, sofern besondere Datenkategorien nach Art. 9 Abs. 1 DSGVO verarbeitet werden. Im Falle einer ausdr\u00FCcklichen Einwilligung in die \u00DCbertragung personenbezogener Daten in Drittstaaten erfolgt die Datenverarbeitung au\u00DFerdem auf Grundlage von Art. 49 Abs. 1 lit. a DSGVO. Sofern Sie in die Speicherung von Cookies oder in den Zugriff auf Informationen in Ihr Endger\u00E4t (z. B. via Device-Fingerprinting) eingewilligt haben, erfolgt die Datenverarbeitung zus\u00E4tzlich auf Grundlage von \u00A7 25 Abs. 1 TDDDG. Die Einwilligung ist jederzeit widerrufbar. Sind Ihre Daten zur Vertragserf\u00FCllung oder zur Durchf\u00FChrung vorvertraglicher Ma\u00DFnahmen erforderlich, verarbeiten wir Ihre Daten auf Grundlage des Art. 6 Abs. 1 lit. b DSGVO. Des Weiteren verarbeiten wir Ihre Daten, sofern diese zur Erf\u00FCllung einer rechtlichen Verpflichtung erforderlich sind auf Grundlage von Art. 6 Abs. 1 lit. c DSGVO. Die Datenverarbeitung kann ferner auf Grundlage unseres berechtigten Interesses nach Art. 6 Abs. 1 lit. f DSGVO erfolgen. \u00DCber die jeweils im Einzelfall einschl\u00E4gigen Rechtsgrundlagen wird in den folgenden Abs\u00E4tzen dieser Datenschutzerkl\u00E4rung informiert.</p>'

+ '<p><strong>Datenschutzbeauftragter</strong></p>'
+ '<p>Wir haben einen Datenschutzbeauftragten benannt.</p>'
+ '<p><strong>\u00D6ffentlicher Datenschutzbeauftragter Altenkirchen:</strong><br>'
+ 'Parkstra\u00DFe 1<br>'
+ '57610 Altenkirchen<br>'
+ 'Telefon: 02681 81-3636<br>'
+ 'E-Mail: <a href="mailto:datenschutz@kreis-ak.de">datenschutz@kreis-ak.de</a></p>'
+ '<p><strong>Datenschutzbeauftragter der Kreisverwaltung Neuwied:</strong><br>'
+ 'Kreisverwaltung Neuwied<br>'
+ 'Herr Christian Fu\u00DF<br>'
+ 'Wilhelm-Leuschner-Stra\u00DFe 9<br>'
+ '56564 Neuwied<br>'
+ 'Telefon: 02631 803-435<br>'
+ 'Telefax: 02631 80393-435<br>'
+ 'E-Mail: <a href="mailto:Christian.Fuss@kreis-neuwied.de">Christian.Fuss@kreis-neuwied.de</a></p>'
+ '<p><strong>Beh\u00F6rdlicher Datenschutzbeauftragter Westerwaldkreis:</strong><br>'
+ 'Sabine Schulz-Lauth<br>'
+ 'Telefon: 02602 124 - 792<br>'
+ 'E-Mail: <a href="mailto:Sabine.Schulz-Lauth@westerwaldkreis.de">Sabine.Schulz-Lauth@westerwaldkreis.de</a></p>'

+ '<p><strong>Empf\u00E4nger von personenbezogenen Daten</strong></p>'
+ '<p>Im Rahmen unserer Gesch\u00E4ftst\u00E4tigkeit arbeiten wir mit verschiedenen externen Stellen zusammen. Dabei ist teilweise auch eine \u00DCbermittlung von personenbezogenen Daten an diese externen Stellen erforderlich. Wir geben personenbezogene Daten nur dann an externe Stellen weiter, wenn dies im Rahmen einer Vertragserf\u00FCllung erforderlich ist, wenn wir gesetzlich hierzu verpflichtet sind (z. B. Weitergabe von Daten an Steuerbeh\u00F6rden), wenn wir ein berechtigtes Interesse nach Art. 6 Abs. 1 lit. f DSGVO an der Weitergabe haben oder wenn eine sonstige Rechtsgrundlage die Datenweitergabe erlaubt. Beim Einsatz von Auftragsverarbeitern geben wir personenbezogene Daten unserer Kunden nur auf Grundlage eines g\u00FCltigen Vertrags \u00FCber Auftragsverarbeitung weiter. Im Falle einer gemeinsamen Verarbeitung wird ein Vertrag \u00FCber gemeinsame Verarbeitung geschlossen.</p>'

+ '<p><strong>Widerruf Ihrer Einwilligung zur Datenverarbeitung</strong></p>'
+ '<p>Viele Datenverarbeitungsvorg\u00E4nge sind nur mit Ihrer ausdr\u00FCcklichen Einwilligung m\u00F6glich. Sie k\u00F6nnen eine bereits erteilte Einwilligung jederzeit widerrufen. Die Rechtm\u00E4\u00DFigkeit der bis zum Widerruf erfolgten Datenverarbeitung bleibt vom Widerruf unber\u00FChrt.</p>'

+ '<p><strong>Widerspruchsrecht gegen die Datenerhebung in besonderen F\u00E4llen sowie gegen Direktwerbung (Art. 21 DSGVO)</strong></p>'
+ '<p>WENN DIE DATENVERARBEITUNG AUF GRUNDLAGE VON ART. 6 ABS. 1 LIT. E ODER F DSGVO ERFOLGT, HABEN SIE JEDERZEIT DAS RECHT, AUS GR\u00DCNDEN, DIE SICH AUS IHRER BESONDEREN SITUATION ERGEBEN, GEGEN DIE VERARBEITUNG IHRER PERSONENBEZOGENEN DATEN WIDERSPRUCH EINZULEGEN; DIES GILT AUCH F\u00DCR EIN AUF DIESE BESTIMMUNGEN GEST\u00DCTZTES PROFILING. DIE JEWEILIGE RECHTSGRUNDLAGE, AUF DENEN EINE VERARBEITUNG BERUHT, ENTNEHMEN SIE DIESER DATENSCHUTZERKL\u00C4RUNG. WENN SIE WIDERSPRUCH EINLEGEN, WERDEN WIR IHRE BETROFFENEN PERSONENBEZOGENEN DATEN NICHT MEHR VERARBEITEN, ES SEI DENN, WIR K\u00D6NNEN ZWINGENDE SCHUTZW\u00DCRDIGE GR\u00DCNDE F\u00DCR DIE VERARBEITUNG NACHWEISEN, DIE IHRE INTERESSEN, RECHTE UND FREIHEITEN \u00DCBERWIEGEN ODER DIE VERARBEITUNG DIENT DER GELTENDMACHUNG, AUS\u00DCBUNG ODER VERTEIDIGUNG VON RECHTSANSPR\u00DCCHEN (WIDERSPRUCH NACH ART. 21 ABS. 1 DSGVO).</p>'
+ '<p>WERDEN IHRE PERSONENBEZOGENEN DATEN VERARBEITET, UM DIREKTWERBUNG ZU BETREIBEN, SO HABEN SIE DAS RECHT, JEDERZEIT WIDERSPRUCH GEGEN DIE VERARBEITUNG SIE BETREFFENDER PERSONENBEZOGENER DATEN ZUM ZWECKE DERARTIGER WERBUNG EINZULEGEN; DIES GILT AUCH F\u00DCR DAS PROFILING, SOWEIT ES MIT SOLCHER DIREKTWERBUNG IN VERBINDUNG STEHT. WENN SIE WIDERSPRECHEN, WERDEN IHRE PERSONENBEZOGENEN DATEN ANSCHLIESSEND NICHT MEHR ZUM ZWECKE DER DIREKTWERBUNG VERWENDET (WIDERSPRUCH NACH ART. 21 ABS. 2 DSGVO).</p>'

+ '<p><strong>Beschwerderecht bei der zust\u00E4ndigen Aufsichtsbeh\u00F6rde</strong></p>'
+ '<p>Im Falle von Verst\u00F6\u00DFen gegen die DSGVO steht den Betroffenen ein Beschwerderecht bei einer Aufsichtsbeh\u00F6rde, insbesondere in dem Mitgliedstaat ihres gew\u00F6hnlichen Aufenthalts, ihres Arbeitsplatzes oder des Orts des mutma\u00DFlichen Versto\u00DFes zu. Das Beschwerderecht besteht unbeschadet anderweitiger verwaltungsrechtlicher oder gerichtlicher Rechtsbehelfe.</p>'

+ '<p><strong>Recht auf Daten\u00FCbertragbarkeit</strong></p>'
+ '<p>Sie haben das Recht, Daten, die wir auf Grundlage Ihrer Einwilligung oder in Erf\u00FCllung eines Vertrags automatisiert verarbeiten, an sich oder an einen Dritten in einem g\u00E4ngigen, maschinenlesbaren Format aush\u00E4ndigen zu lassen. Sofern Sie die direkte \u00DCbertragung der Daten an einen anderen Verantwortlichen verlangen, erfolgt dies nur, soweit es technisch machbar ist.</p>'

+ '<p><strong>Auskunft, Berichtigung und L\u00F6schung</strong></p>'
+ '<p>Sie haben im Rahmen der geltenden gesetzlichen Bestimmungen jederzeit das Recht auf unentgeltliche Auskunft \u00FCber Ihre gespeicherten personenbezogenen Daten, deren Herkunft und Empf\u00E4nger und den Zweck der Datenverarbeitung und ggf. ein Recht auf Berichtigung oder L\u00F6schung dieser Daten. Hierzu sowie zu weiteren Fragen zum Thema personenbezogene Daten k\u00F6nnen Sie sich jederzeit an uns wenden.</p>'

+ '<p><strong>Recht auf Einschr\u00E4nkung der Verarbeitung</strong></p>'
+ '<p>Sie haben das Recht, die Einschr\u00E4nkung der Verarbeitung Ihrer personenbezogenen Daten zu verlangen. Hierzu k\u00F6nnen Sie sich jederzeit an uns wenden. Das Recht auf Einschr\u00E4nkung der Verarbeitung besteht in folgenden F\u00E4llen:</p>'
+ '<ul>'
+ '<li>Wenn Sie die Richtigkeit Ihrer bei uns gespeicherten personenbezogenen Daten bestreiten, ben\u00F6tigen wir in der Regel Zeit, um dies zu \u00FCberpr\u00FCfen. F\u00FCr die Dauer der Pr\u00FCfung haben Sie das Recht, die Einschr\u00E4nkung der Verarbeitung Ihrer personenbezogenen Daten zu verlangen.</li>'
+ '<li>Wenn die Verarbeitung Ihrer personenbezogenen Daten unrechtm\u00E4\u00DFig geschah/geschieht, k\u00F6nnen Sie statt der L\u00F6schung die Einschr\u00E4nkung der Datenverarbeitung verlangen.</li>'
+ '<li>Wenn wir Ihre personenbezogenen Daten nicht mehr ben\u00F6tigen, Sie sie jedoch zur Aus\u00FCbung, Verteidigung oder Geltendmachung von Rechtsanspr\u00FCchen ben\u00F6tigen, haben Sie das Recht, statt der L\u00F6schung die Einschr\u00E4nkung der Verarbeitung Ihrer personenbezogenen Daten zu verlangen.</li>'
+ '<li>Wenn Sie einen Widerspruch nach Art. 21 Abs. 1 DSGVO eingelegt haben, muss eine Abw\u00E4gung zwischen Ihren und unseren Interessen vorgenommen werden. Solange noch nicht feststeht, wessen Interessen \u00FCberwiegen, haben Sie das Recht, die Einschr\u00E4nkung der Verarbeitung Ihrer personenbezogenen Daten zu verlangen.</li>'
+ '</ul>'
+ '<p>Wenn Sie die Verarbeitung Ihrer personenbezogenen Daten eingeschr\u00E4nkt haben, d\u00FCrfen diese Daten \u2013 von ihrer Speicherung abgesehen \u2013 nur mit Ihrer Einwilligung oder zur Geltendmachung, Aus\u00FCbung oder Verteidigung von Rechtsanspr\u00FCchen oder zum Schutz der Rechte einer anderen nat\u00FCrlichen oder juristischen Person oder aus Gr\u00FCnden eines wichtigen \u00F6ffentlichen Interesses der Europ\u00E4ischen Union oder eines Mitgliedstaats verarbeitet werden.</p>'

+ '<p><strong>SSL- bzw. TLS-Verschl\u00FCsselung</strong></p>'
+ '<p>Diese Seite nutzt aus Sicherheitsgr\u00FCnden und zum Schutz der \u00DCbertragung vertraulicher Inhalte, wie zum Beispiel Bestellungen oder Anfragen, die Sie an uns als Seitenbetreiber senden, eine SSL- bzw. TLS-Verschl\u00FCsselung. Eine verschl\u00FCsselte Verbindung erkennen Sie daran, dass die Adresszeile des Browsers von \u201Ehttp://\u201C auf \u201Ehttps://\u201C wechselt und an dem Schloss-Symbol in Ihrer Browserzeile.</p>'
+ '<p>Wenn die SSL- bzw. TLS-Verschl\u00FCsselung aktiviert ist, k\u00F6nnen die Daten, die Sie an uns \u00FCbermitteln, nicht von Dritten mitgelesen werden.</p>'

+ '<h3>4. Datenerfassung auf dieser Website</h3>'

+ '<p><strong>Cookies</strong></p>'
+ '<p>Unsere Internetseiten verwenden so genannte \u201ECookies\u201C. Cookies sind kleine Datenpakete und richten auf Ihrem Endger\u00E4t keinen Schaden an. Sie werden entweder vor\u00FCbergehend f\u00FCr die Dauer einer Sitzung (Session-Cookies) oder dauerhaft (permanente Cookies) auf Ihrem Endger\u00E4t gespeichert. Session-Cookies werden nach Ende Ihres Besuchs automatisch gel\u00F6scht. Permanente Cookies bleiben auf Ihrem Endger\u00E4t gespeichert, bis Sie diese selbst l\u00F6schen oder eine automatische L\u00F6schung durch Ihren Webbrowser erfolgt.</p>'
+ '<p>Cookies k\u00F6nnen von uns (First-Party-Cookies) oder von Drittunternehmen stammen (sog. Third-Party-Cookies). Third-Party-Cookies erm\u00F6glichen die Einbindung bestimmter Dienstleistungen von Drittunternehmen innerhalb von Webseiten (z. B. Cookies zur Abwicklung von Zahlungsdienstleistungen).</p>'
+ '<p>Cookies haben verschiedene Funktionen. Zahlreiche Cookies sind technisch notwendig, da bestimmte Webseitenfunktionen ohne diese nicht funktionieren w\u00FCrden (z. B. die Warenkorbfunktion oder die Anzeige von Videos). Andere Cookies k\u00F6nnen zur Auswertung des Nutzerverhaltens oder zu Werbezwecken verwendet werden.</p>'
+ '<p>Cookies, die zur Durchf\u00FChrung des elektronischen Kommunikationsvorgangs, zur Bereitstellung bestimmter, von Ihnen erw\u00FCnschter Funktionen (z. B. f\u00FCr die Warenkorbfunktion) oder zur Optimierung der Website (z. B. Cookies zur Messung des Webpublikums) erforderlich sind (notwendige Cookies), werden auf Grundlage von Art. 6 Abs. 1 lit. f DSGVO gespeichert, sofern keine andere Rechtsgrundlage angegeben wird. Der Websitebetreiber hat ein berechtigtes Interesse an der Speicherung von notwendigen Cookies zur technisch fehlerfreien und optimierten Bereitstellung seiner Dienste. Sofern eine Einwilligung zur Speicherung von Cookies und vergleichbaren Wiedererkennungstechnologien abgefragt wurde, erfolgt die Verarbeitung ausschlie\u00DFlich auf Grundlage dieser Einwilligung (Art. 6 Abs. 1 lit. a DSGVO und \u00A7 25 Abs. 1 TDDDG); die Einwilligung ist jederzeit widerrufbar.</p>'
+ '<p>Sie k\u00F6nnen Ihren Browser so einstellen, dass Sie \u00FCber das Setzen von Cookies informiert werden und Cookies nur im Einzelfall erlauben, die Annahme von Cookies f\u00FCr bestimmte F\u00E4lle oder generell ausschlie\u00DFen sowie das automatische L\u00F6schen der Cookies beim Schlie\u00DFen des Browsers aktivieren. Bei der Deaktivierung von Cookies kann die Funktionalit\u00E4t dieser Website eingeschr\u00E4nkt sein.</p>'
+ '<p>Welche Cookies und Dienste auf dieser Website eingesetzt werden, k\u00F6nnen Sie dieser Datenschutzerkl\u00E4rung entnehmen.</p>'

+ '<p><strong>CCM19</strong></p>'
+ '<p>Unsere Website nutzt CCM19, um Ihre Einwilligung zur Speicherung bestimmter Cookies auf Ihrem Endger\u00E4t oder zum Einsatz bestimmter Technologien einzuholen und diese datenschutzkonform zu dokumentieren. Anbieter dieser Technologie ist Papoo Software &amp; Media GmbH, Auguststr. 4, 53229 Bonn (im Folgenden \u201ECCM19\u201C).</p>'
+ '<p>Wenn Sie unsere Website betreten, wird eine Verbindung zu den Servern von CCM19 hergestellt, um Ihre Einwilligungen und sonstigen Erkl\u00E4rungen zur Cookie-Nutzung einzuholen. Anschlie\u00DFend speichert CCM19 einen Cookie in Ihrem Browser, um Ihnen die erteilten Einwilligungen bzw. deren Widerruf zuordnen zu k\u00F6nnen. Die so erfassten Daten werden gespeichert, bis Sie uns zur L\u00F6schung auffordern, den CCM19-Cookie selbst l\u00F6schen oder der Zweck f\u00FCr die Datenspeicherung entf\u00E4llt. Zwingende gesetzliche Aufbewahrungspflichten bleiben unber\u00FChrt.</p>'
+ '<p>Der Einsatz von CCM19 erfolgt, um die gesetzlich vorgeschriebenen Einwilligungen f\u00FCr den Einsatz von Cookies einzuholen. Rechtsgrundlage hierf\u00FCr ist Art. 6 Abs. 1 S. 1 lit. c DSGVO.</p>'

+ '<p><strong>Auftragsverarbeitung</strong></p>'
+ '<p>Wir haben einen Vertrag \u00FCber Auftragsverarbeitung (AVV) zur Nutzung des oben genannten Dienstes geschlossen. Hierbei handelt es sich um einen datenschutzrechtlich vorgeschriebenen Vertrag, der gew\u00E4hrleistet, dass dieser die personenbezogenen Daten unserer Websitebesucher nur nach unseren Weisungen und unter Einhaltung der DSGVO verarbeitet.</p>'

+ '<p><strong>Server-Log-Dateien</strong></p>'
+ '<p>Der Provider der Seiten erhebt und speichert automatisch Informationen in so genannten Server-Log-Dateien, die Ihr Browser automatisch an uns \u00FCbermittelt. Dies sind:</p>'
+ '<ul>'
+ '<li>Browsertyp und Browserversion</li>'
+ '<li>verwendetes Betriebssystem</li>'
+ '<li>Referrer URL</li>'
+ '<li>Hostname des zugreifenden Rechners</li>'
+ '<li>Uhrzeit der Serveranfrage</li>'
+ '<li>IP-Adresse</li>'
+ '</ul>'
+ '<p>Eine Zusammenf\u00FChrung dieser Daten mit anderen Datenquellen wird nicht vorgenommen.</p>'
+ '<p>Die Erfassung dieser Daten erfolgt auf Grundlage von Art. 6 Abs. 1 lit. f DSGVO. Der Websitebetreiber hat ein berechtigtes Interesse an der technisch fehlerfreien Darstellung und der Optimierung seiner Website \u2013 hierzu m\u00FCssen die Server-Log-Files erfasst werden.</p>'

+ '<p><strong>Kontaktformular</strong></p>'
+ '<p>Wenn Sie uns per Kontaktformular Anfragen zukommen lassen, werden Ihre Angaben aus dem Anfrageformular inklusive der von Ihnen dort angegebenen Kontaktdaten zwecks Bearbeitung der Anfrage und f\u00FCr den Fall von Anschlussfragen bei uns gespeichert. Diese Daten geben wir nicht ohne Ihre Einwilligung weiter.</p>'
+ '<p>Die Verarbeitung dieser Daten erfolgt auf Grundlage von Art. 6 Abs. 1 lit. b DSGVO, sofern Ihre Anfrage mit der Erf\u00FCllung eines Vertrags zusammenh\u00E4ngt oder zur Durchf\u00FChrung vorvertraglicher Ma\u00DFnahmen erforderlich ist. In allen \u00FCbrigen F\u00E4llen beruht die Verarbeitung auf unserem berechtigten Interesse an der effektiven Bearbeitung der an uns gerichteten Anfragen (Art. 6 Abs. 1 lit. f DSGVO) oder auf Ihrer Einwilligung (Art. 6 Abs. 1 lit. a DSGVO) sofern diese abgefragt wurde; die Einwilligung ist jederzeit widerrufbar.</p>'
+ '<p>Die von Ihnen im Kontaktformular eingegebenen Daten verbleiben bei uns, bis Sie uns zur L\u00F6schung auffordern, Ihre Einwilligung zur Speicherung widerrufen oder der Zweck f\u00FCr die Datenspeicherung entf\u00E4llt (z. B. nach abgeschlossener Bearbeitung Ihrer Anfrage). Zwingende gesetzliche Bestimmungen \u2013 insbesondere Aufbewahrungsfristen \u2013 bleiben unber\u00FChrt.</p>'

+ '<p><strong>Anfrage per E-Mail, Telefon oder Telefax</strong></p>'
+ '<p>Wenn Sie uns per E-Mail, Telefon oder Telefax kontaktieren, wird Ihre Anfrage inklusive aller daraus hervorgehenden personenbezogenen Daten (Name, Anfrage) zum Zwecke der Bearbeitung Ihres Anliegens bei uns gespeichert und verarbeitet. Diese Daten geben wir nicht ohne Ihre Einwilligung weiter.</p>'
+ '<p>Die Verarbeitung dieser Daten erfolgt auf Grundlage von Art. 6 Abs. 1 lit. b DSGVO, sofern Ihre Anfrage mit der Erf\u00FCllung eines Vertrags zusammenh\u00E4ngt oder zur Durchf\u00FChrung vorvertraglicher Ma\u00DFnahmen erforderlich ist. In allen \u00FCbrigen F\u00E4llen beruht die Verarbeitung auf unserem berechtigten Interesse an der effektiven Bearbeitung der an uns gerichteten Anfragen (Art. 6 Abs. 1 lit. f DSGVO) oder auf Ihrer Einwilligung (Art. 6 Abs. 1 lit. a DSGVO) sofern diese abgefragt wurde; die Einwilligung ist jederzeit widerrufbar.</p>'
+ '<p>Die von Ihnen an uns per Kontaktanfragen \u00FCbersandten Daten verbleiben bei uns, bis Sie uns zur L\u00F6schung auffordern, Ihre Einwilligung zur Speicherung widerrufen oder der Zweck f\u00FCr die Datenspeicherung entf\u00E4llt (z. B. nach abgeschlossener Bearbeitung Ihres Anliegens). Zwingende gesetzliche Bestimmungen \u2013 insbesondere gesetzliche Aufbewahrungsfristen \u2013 bleiben unber\u00FChrt.</p>'

+ '<p><strong>Registrierung auf dieser Website</strong></p>'
+ '<p>Sie k\u00F6nnen sich auf dieser Website registrieren, um zus\u00E4tzliche Funktionen auf der Seite zu nutzen. Die dazu eingegebenen Daten verwenden wir nur zum Zwecke der Nutzung des jeweiligen Angebotes oder Dienstes, f\u00FCr den Sie sich registriert haben. Die bei der Registrierung abgefragten Pflichtangaben m\u00FCssen vollst\u00E4ndig angegeben werden. Anderenfalls werden wir die Registrierung ablehnen.</p>'
+ '<p>F\u00FCr wichtige \u00C4nderungen etwa beim Angebotsumfang oder bei technisch notwendigen \u00C4nderungen nutzen wir die bei der Registrierung angegebene E-Mail-Adresse, um Sie auf diesem Wege zu informieren.</p>'
+ '<p>Die Verarbeitung der bei der Registrierung eingegebenen Daten erfolgt zum Zwecke der Durchf\u00FChrung des durch die Registrierung begr\u00FCndeten Nutzungsverh\u00E4ltnisses und ggf. zur Anbahnung weiterer Vertr\u00E4ge (Art. 6 Abs. 1 lit. b DSGVO).</p>'
+ '<p>Die bei der Registrierung erfassten Daten werden von uns gespeichert, solange Sie auf dieser Website registriert sind und werden anschlie\u00DFend gel\u00F6scht. Gesetzliche Aufbewahrungsfristen bleiben unber\u00FChrt.</p>'

+ '<h3>5. Newsletter</h3>'
+ '<p><strong>Newsletterdaten</strong></p>'
+ '<p>Wenn Sie den auf der Website angebotenen Newsletter beziehen m\u00F6chten, ben\u00F6tigen wir von Ihnen eine E-Mail-Adresse sowie Informationen, welche uns die \u00DCberpr\u00FCfung gestatten, dass Sie der Inhaber der angegebenen E-Mail-Adresse sind und mit dem Empfang des Newsletters einverstanden sind. Weitere Daten werden nicht bzw. nur auf freiwilliger Basis erhoben. Diese Daten verwenden wir ausschlie\u00DFlich f\u00FCr den Versand der angeforderten Informationen und geben diese nicht an Dritte weiter.</p>'
+ '<p>Die Verarbeitung der in das Newsletteranmeldeformular eingegebenen Daten erfolgt ausschlie\u00DFlich auf Grundlage Ihrer Einwilligung (Art. 6 Abs. 1 lit. a DSGVO). Die erteilte Einwilligung zur Speicherung der Daten, der E-Mail-Adresse sowie deren Nutzung zum Versand des Newsletters k\u00F6nnen Sie jederzeit widerrufen, etwa \u00FCber den \u201EAustragen\u201C-Link im Newsletter. Die Rechtm\u00E4\u00DFigkeit der bereits erfolgten Datenverarbeitungsvorg\u00E4nge bleibt vom Widerruf unber\u00FChrt.</p>'
+ '<p>Die von Ihnen zum Zwecke des Newsletter-Bezugs bei uns hinterlegten Daten werden von uns bis zu Ihrer Austragung aus dem Newsletter bei uns bzw. dem Newsletterdiensteanbieter gespeichert und nach der Abbestellung des Newsletters oder nach Zweckfortfall aus der Newsletterverteilerliste gel\u00F6scht. Wir behalten uns vor, E-Mail-Adressen aus unserem Newsletterverteiler nach eigenem Ermessen im Rahmen unseres berechtigten Interesses nach Art. 6 Abs. 1 lit. f DSGVO zu l\u00F6schen oder zu sperren.</p>'
+ '<p>Daten, die zu anderen Zwecken bei uns gespeichert wurden, bleiben hiervon unber\u00FChrt.</p>'
+ '<p>Nach Ihrer Austragung aus der Newsletterverteilerliste wird Ihre E-Mail-Adresse bei uns bzw. dem Newsletterdiensteanbieter ggf. in einer Blacklist gespeichert, sofern dies zur Verhinderung k\u00FCnftiger Mailings erforderlich ist. Die Daten aus der Blacklist werden nur f\u00FCr diesen Zweck verwendet und nicht mit anderen Daten zusammengef\u00FChrt. Dies dient sowohl Ihrem Interesse als auch unserem Interesse an der Einhaltung der gesetzlichen Vorgaben beim Versand von Newslettern (berechtigtes Interesse im Sinne des Art. 6 Abs. 1 lit. f DSGVO). Die Speicherung in der Blacklist ist zeitlich nicht befristet. Sie k\u00F6nnen der Speicherung widersprechen, sofern Ihre Interessen unser berechtigtes Interesse \u00FCberwiegen.</p>'

+ '<h3>6. Plugins und Tools</h3>'

+ '<p><strong>YouTube mit erweitertem Datenschutz</strong></p>'
+ '<p>Diese Website bindet Videos der Website YouTube ein. Betreiber der Website ist die Google Ireland Limited (\u201EGoogle\u201D), Gordon House, Barrow Street, Dublin 4, Irland.</p>'
+ '<p>Wenn Sie eine dieser Website besuchen, auf denen YouTube eingebunden ist, wird eine Verbindung zu den Servern von YouTube hergestellt. Dabei wird dem YouTube-Server mitgeteilt, welche unserer Seiten Sie besucht haben. Wenn Sie in Ihrem YouTube-Account eingeloggt sind, erm\u00F6glichen Sie YouTube, Ihr Surfverhalten direkt Ihrem pers\u00F6nlichen Profil zuzuordnen. Dies k\u00F6nnen Sie verhindern, indem Sie sich aus Ihrem YouTube-Account ausloggen.</p>'
+ '<p>Wir nutzen YouTube im erweiterten Datenschutzmodus. Videos, die im erweiterten Datenschutzmodus abgespielt werden, werden nach Aussage von YouTube nicht zur Personalisierung des Surfens auf YouTube eingesetzt. Anzeigen, die im erweiterten Datenschutzmodus ausgespielt werden, sind ebenfalls nicht personalisiert. Im erweiterten Datenschutzmodus werden keine Cookies gesetzt. Stattdessen werden jedoch sogenannte Local Storage Elemente im Browser des Users gespeichert, die \u00E4hnlich wie Cookies personenbezogene Daten beinhalten und zur Wiedererkennung eingesetzt werden k\u00F6nnen. Details zum erweiterten Datenschutzmodus finden Sie hier: <a href="https://support.google.com/youtube/answer/171780" target="_blank" rel="noopener">https://support.google.com/youtube/answer/171780</a>.</p>'
+ '<p>Gegebenenfalls k\u00F6nnen nach der Aktivierung eines YouTube-Videos weitere Datenverarbeitungsvorg\u00E4nge ausgel\u00F6st werden, auf die wir keinen Einfluss haben.</p>'
+ '<p>Die Nutzung von YouTube erfolgt im Interesse einer ansprechenden Darstellung unserer Online-Angebote. Dies stellt ein berechtigtes Interesse im Sinne von Art. 6 Abs. 1 lit. f DSGVO dar. Sofern eine entsprechende Einwilligung abgefragt wurde, erfolgt die Verarbeitung ausschlie\u00DFlich auf Grundlage von Art. 6 Abs. 1 lit. a DSGVO und \u00A7 25 Abs. 1 TDDDG, soweit die Einwilligung die Speicherung von Cookies oder den Zugriff auf Informationen im Endger\u00E4t des Nutzers (z. B. Device-Fingerprinting) im Sinne des TDDDG umfasst. Die Einwilligung ist jederzeit widerrufbar.</p>'
+ '<p>Weitere Informationen \u00FCber Datenschutz bei YouTube finden Sie in deren Datenschutzerkl\u00E4rung unter: <a href="https://policies.google.com/privacy?hl=de" target="_blank" rel="noopener">https://policies.google.com/privacy?hl=de</a>.</p>'
+ '<p>Das Unternehmen verf\u00FCgt \u00FCber eine Zertifizierung nach dem \u201EEU-US Data Privacy Framework\u201C (DPF). Der DPF ist ein \u00DCbereinkommen zwischen der Europ\u00E4ischen Union und den USA, der die Einhaltung europ\u00E4ischer Datenschutzstandards bei Datenverarbeitungen in den USA gew\u00E4hrleisten soll. Jedes nach dem DPF zertifizierte Unternehmen verpflichtet sich, diese Datenschutzstandards einzuhalten. Weitere Informationen hierzu erhalten Sie vom Anbieter unter folgendem Link: <a href="https://www.dataprivacyframework.gov/participant/5780" target="_blank" rel="noopener">https://www.dataprivacyframework.gov/participant/5780</a>.</p>'

+ '<p><strong>Google Fonts (lokales Hosting)</strong></p>'
+ '<p>Diese Seite nutzt zur einheitlichen Darstellung von Schriftarten so genannte Google Fonts, die von Google bereitgestellt werden. Die Google Fonts sind lokal installiert. Eine Verbindung zu Servern von Google findet dabei nicht statt.</p>'
+ '<p>Weitere Informationen zu Google Fonts finden Sie unter <a href="https://developers.google.com/fonts/faq" target="_blank" rel="noopener">https://developers.google.com/fonts/faq</a> und in der Datenschutzerkl\u00E4rung von Google: <a href="https://policies.google.com/privacy?hl=de" target="_blank" rel="noopener">https://policies.google.com/privacy?hl=de</a>.</p>'

+ '<p><strong>Google Maps</strong></p>'
+ '<p>Diese Seite nutzt den Kartendienst Google Maps. Anbieter ist die Google Ireland Limited (\u201EGoogle\u201C), Gordon House, Barrow Street, Dublin 4, Irland. Mit Hilfe dieses Dienstes k\u00F6nnen wir Kartenmaterial auf unserer Website einbinden.</p>'
+ '<p>Zur Nutzung der Funktionen von Google Maps ist es notwendig, Ihre IP-Adresse zu speichern. Diese Informationen werden in der Regel an einen Server von Google in den USA \u00FCbertragen und dort gespeichert. Der Anbieter dieser Seite hat keinen Einfluss auf diese Daten\u00FCbertragung. Wenn Google Maps aktiviert ist, kann Google zum Zwecke der einheitlichen Darstellung der Schriftarten Google Fonts verwenden. Beim Aufruf von Google Maps l\u00E4dt Ihr Browser die ben\u00F6tigten Web Fonts in ihren Browsercache, um Texte und Schriftarten korrekt anzuzeigen.</p>'
+ '<p>Die Nutzung von Google Maps erfolgt im Interesse einer ansprechenden Darstellung unserer Online-Angebote und an einer leichten Auffindbarkeit der von uns auf der Website angegebenen Orte. Dies stellt ein berechtigtes Interesse im Sinne von Art. 6 Abs. 1 lit. f DSGVO dar. Sofern eine entsprechende Einwilligung abgefragt wurde, erfolgt die Verarbeitung ausschlie\u00DFlich auf Grundlage von Art. 6 Abs. 1 lit. a DSGVO und \u00A7 25 Abs. 1 TDDDG, soweit die Einwilligung die Speicherung von Cookies oder den Zugriff auf Informationen im Endger\u00E4t des Nutzers (z. B. Device-Fingerprinting) im Sinne des TDDDG umfasst. Die Einwilligung ist jederzeit widerrufbar.</p>'
+ '<p>Die Daten\u00FCbertragung in die USA wird auf die Standardvertragsklauseln der EU-Kommission gest\u00FCtzt. Details finden Sie hier: <a href="https://privacy.google.com/businesses/gdprcontrollerterms/" target="_blank" rel="noopener">https://privacy.google.com/businesses/gdprcontrollerterms/</a> und <a href="https://privacy.google.com/businesses/gdprcontrollerterms/sccs/" target="_blank" rel="noopener">https://privacy.google.com/businesses/gdprcontrollerterms/sccs/</a>.</p>'
+ '<p>Mehr Informationen zum Umgang mit Nutzerdaten finden Sie in der Datenschutzerkl\u00E4rung von Google: <a href="https://policies.google.com/privacy?hl=de" target="_blank" rel="noopener">https://policies.google.com/privacy?hl=de</a>.</p>'
+ '<p>Das Unternehmen verf\u00FCgt \u00FCber eine Zertifizierung nach dem \u201EEU-US Data Privacy Framework\u201C (DPF). Weitere Informationen hierzu erhalten Sie vom Anbieter unter folgendem Link: <a href="https://www.dataprivacyframework.gov/participant/5780" target="_blank" rel="noopener">https://www.dataprivacyframework.gov/participant/5780</a>.</p>'

+ '<h3>7. Audio- und Videokonferenzen</h3>'
+ '<p><strong>Datenverarbeitung</strong></p>'
+ '<p>F\u00FCr die Kommunikation mit unseren Kunden setzen wir unter anderen Online-Konferenz-Tools ein. Die im Einzelnen von uns genutzten Tools sind unten aufgelistet. Wenn Sie mit uns per Video- oder Audiokonferenz via Internet kommunizieren, werden Ihre personenbezogenen Daten von uns und dem Anbieter des jeweiligen Konferenz-Tools erfasst und verarbeitet.</p>'
+ '<p>Die Konferenz-Tools erfassen dabei alle Daten, die Sie zur Nutzung der Tools bereitstellen/einsetzen (E-Mail-Adresse und/oder Ihre Telefonnummer). Ferner verarbeiten die Konferenz-Tools die Dauer der Konferenz, Beginn und Ende (Zeit) der Teilnahme an der Konferenz, Anzahl der Teilnehmer und sonstige \u201EKontextinformationen\u201C im Zusammenhang mit dem Kommunikationsvorgang (Metadaten).</p>'
+ '<p>Des Weiteren verarbeitet der Anbieter des Tools alle technischen Daten, die zur Abwicklung der Online-Kommunikation erforderlich sind. Dies umfasst insbesondere IP-Adressen, MAC-Adressen, Ger\u00E4te-IDs, Ger\u00E4tetyp, Betriebssystemtyp und -version, Client-Version, Kameratyp, Mikrofon oder Lautsprecher sowie die Art der Verbindung.</p>'
+ '<p>Sofern innerhalb des Tools Inhalte ausgetauscht, hochgeladen oder in sonstiger Weise bereitgestellt werden, werden diese ebenfalls auf den Servern der Tool-Anbieter gespeichert. Zu solchen Inhalten z\u00E4hlen insbesondere Cloud-Aufzeichnungen, Chat-/ Sofortnachrichten, Voicemails hochgeladene Fotos und Videos, Dateien, Whiteboards und andere Informationen, die w\u00E4hrend der Nutzung des Dienstes geteilt werden.</p>'
+ '<p>Bitte beachten Sie, dass wir nicht vollumf\u00E4nglich Einfluss auf die Datenverarbeitungsvorg\u00E4nge der verwendeten Tools haben. Unsere M\u00F6glichkeiten richten sich ma\u00DFgeblich nach der Unternehmenspolitik des jeweiligen Anbieters. Weitere Hinweise zur Datenverarbeitung durch die Konferenztools entnehmen Sie den Datenschutzerkl\u00E4rungen der jeweils eingesetzten Tools, die wir unter diesem Text aufgef\u00FChrt haben.</p>'

+ '<p><strong>Zweck und Rechtsgrundlagen</strong></p>'
+ '<p>Die Konferenz-Tools werden genutzt, um mit angehenden oder bestehenden Vertragspartnern zu kommunizieren oder bestimmte Leistungen gegen\u00FCber unseren Kunden anzubieten (Art. 6 Abs. 1 lit. b DSGVO). Des Weiteren dient der Einsatz der Tools der allgemeinen Vereinfachung und Beschleunigung der Kommunikation mit uns bzw. unserem Unternehmen (berechtigtes Interesse im Sinne von Art. 6 Abs. 1 lit. f DSGVO). Soweit eine Einwilligung abgefragt wurde, erfolgt der Einsatz der betreffenden Tools auf Grundlage dieser Einwilligung; die Einwilligung ist jederzeit mit Wirkung f\u00FCr die Zukunft widerrufbar.</p>'

+ '<p><strong>Speicherdauer</strong></p>'
+ '<p>Die unmittelbar von uns \u00FCber die Video- und Konferenz-Tools erfassten Daten werden von unseren Systemen gel\u00F6scht, sobald Sie uns zur L\u00F6schung auffordern, Ihre Einwilligung zur Speicherung widerrufen oder der Zweck f\u00FCr die Datenspeicherung entf\u00E4llt. Gespeicherte Cookies verbleiben auf Ihrem Endger\u00E4t, bis Sie sie l\u00F6schen. Zwingende gesetzliche Aufbewahrungsfristen bleiben unber\u00FChrt.</p>'
+ '<p>Auf die Speicherdauer Ihrer Daten, die von den Betreibern der Konferenz-Tools zu eigenen Zwecken gespeichert werden, haben wir keinen Einfluss. F\u00FCr Einzelheiten dazu informieren Sie sich bitte direkt bei den Betreibern der Konferenz-Tools.</p>'

+ '<p><strong>Eingesetzte Konferenz-Tools \u2013 Microsoft Teams</strong></p>'
+ '<p>Wir nutzen Microsoft Teams. Anbieter ist die Microsoft Ireland Operations Limited, One Microsoft Place, South County Business Park, Leopardstown, Dublin 18, Irland. Details zur Datenverarbeitung entnehmen Sie der Datenschutzerkl\u00E4rung von Microsoft Teams: <a href="https://privacy.microsoft.com/de-de/privacystatement" target="_blank" rel="noopener">https://privacy.microsoft.com/de-de/privacystatement</a>.</p>'
+ '<p>Das Unternehmen verf\u00FCgt \u00FCber eine Zertifizierung nach dem \u201EEU-US Data Privacy Framework\u201C (DPF). Weitere Informationen hierzu erhalten Sie vom Anbieter unter folgendem Link: <a href="https://www.dataprivacyframework.gov/participant/6474" target="_blank" rel="noopener">https://www.dataprivacyframework.gov/participant/6474</a>.</p>'

+ '<p><strong>Auftragsverarbeitung</strong></p>'
+ '<p>Wir haben einen Vertrag \u00FCber Auftragsverarbeitung (AVV) zur Nutzung des oben genannten Dienstes geschlossen. Hierbei handelt es sich um einen datenschutzrechtlich vorgeschriebenen Vertrag, der gew\u00E4hrleistet, dass dieser die personenbezogenen Daten unserer Websitebesucher nur nach unseren Weisungen und unter Einhaltung der DSGVO verarbeitet.</p>'

+ '<h3>8. Unsere Social-Media-Auftritte</h3>'
+ '<p><strong>Datenverarbeitung durch soziale Netzwerke</strong></p>'
+ '<p>Wir unterhalten \u00F6ffentlich zug\u00E4ngliche Profile in sozialen Netzwerken. Die im Einzelnen von uns genutzten sozialen Netzwerke finden Sie weiter unten.</p>'
+ '<p>Soziale Netzwerke wie Facebook, Twitter etc. k\u00F6nnen Ihr Nutzerverhalten in der Regel umfassend analysieren, wenn Sie deren Website oder eine Website mit integrierten Social-Media-Inhalten (z. B. LikeButtons oder Werbebannern) besuchen. Durch den Besuch unserer Social-Media-Pr\u00E4senzen werden zahlreiche datenschutzrelevante Verarbeitungsvorg\u00E4nge ausgel\u00F6st. Im Einzelnen:</p>'
+ '<p>Wenn Sie in Ihrem Social-Media-Account eingeloggt sind und unsere Social-Media-Pr\u00E4senz besuchen, kann der Betreiber des Social-Media-Portals diesen Besuch Ihrem Benutzerkonto zuordnen. Ihre personenbezogenen Daten k\u00F6nnen unter Umst\u00E4nden aber auch dann erfasst werden, wenn Sie nicht eingeloggt sind oder keinen Account beim jeweiligen Social-Media-Portal besitzen. Diese Datenerfassung erfolgt in diesem Fall beispielsweise \u00FCber Cookies, die auf Ihrem Endger\u00E4t gespeichert werden oder durch Erfassung Ihrer IP-Adresse.</p>'
+ '<p>Mit Hilfe der so erfassten Daten k\u00F6nnen die Betreiber der Social-Media-Portale Nutzerprofile erstellen, in denen Ihre Pr\u00E4ferenzen und Interessen hinterlegt sind. Auf diese Weise kann Ihnen interessenbezogene Werbung in- und au\u00DFerhalb der jeweiligen Social-Media-Pr\u00E4senz angezeigt werden. Sofern Sie \u00FCber einen Account beim jeweiligen sozialen Netzwerk verf\u00FCgen, kann die interessenbezogene Werbung auf allen Ger\u00E4ten angezeigt werden, auf denen Sie eingeloggt sind oder eingeloggt waren.</p>'
+ '<p>Bitte beachten Sie au\u00DFerdem, dass wir nicht alle Verarbeitungsprozesse auf den Social-Media-Portalen nachvollziehen k\u00F6nnen. Je nach Anbieter k\u00F6nnen daher ggf. weitere Verarbeitungsvorg\u00E4nge von den Betreibern der Social-Media-Portale durchgef\u00FChrt werden. Details hierzu entnehmen Sie den Nutzungsbedingungen und Datenschutzbestimmungen der jeweiligen Social-Media-Portale.</p>'

+ '<p><strong>Rechtsgrundlage</strong></p>'
+ '<p>Unsere Social-Media-Auftritte sollen eine m\u00F6glichst umfassende Pr\u00E4senz im Internet gew\u00E4hrleisten. Hierbei handelt es sich um ein berechtigtes Interesse im Sinne von Art. 6 Abs. 1 lit. f DSGVO. Die von den sozialen Netzwerken initiierten Analyseprozesse beruhen ggf. auf abweichenden Rechtsgrundlagen, die von den Betreibern der sozialen Netzwerke anzugeben sind (z. B. Einwilligung im Sinne des Art. 6 Abs. 1 lit. A DSGVO).</p>'

+ '<p><strong>Verantwortlicher und Geltendmachung von Rechten</strong></p>'
+ '<p>Wenn Sie einen unserer Social-Media-Auftritte (z. B. Facebook) besuchen, sind wir gemeinsam mit dem Betreiber der Social-Media-Plattform f\u00FCr die bei diesem Besuch ausgel\u00F6sten Datenverarbeitungsvorg\u00E4nge verantwortlich. Sie k\u00F6nnen Ihre Rechte (Auskunft, Berichtigung, L\u00F6schung, Einschr\u00E4nkung der Verarbeitung, Daten\u00FCbertragbarkeit und Beschwerde) grunds\u00E4tzlich sowohl gg\u00FC. uns als auch gg\u00FC. dem Betreiber des jeweiligen Social-Media-Portals (z. B. gg\u00FC. Facebook) geltend machen.</p>'
+ '<p>Bitte beachten Sie, dass wir trotz der gemeinsamen Verantwortlichkeit mit den Social-Media-Portal-Betreibern nicht vollumf\u00E4nglich Einfluss auf die Datenverarbeitungsvorg\u00E4nge der Social-Media-Portale haben. Unsere M\u00F6glichkeiten richten sich ma\u00DFgeblich nach der Unternehmenspolitik des jeweiligen Anbieters.</p>'

+ '<p><strong>Speicherdauer</strong></p>'
+ '<p>Die unmittelbar von uns \u00FCber die Social-Media-Pr\u00E4senz erfassten Daten werden von unseren Systemen gel\u00F6scht, sobald der Zweck f\u00FCr ihre Speicherung entf\u00E4llt, Sie uns zur L\u00F6schung auffordern, Ihre Einwilligung zur Speicherung widerrufen oder der Zweck f\u00FCr die Datenspeicherung entf\u00E4llt. Gespeicherte Cookies verbleiben auf Ihrem Endger\u00E4t, bis Sie sie l\u00F6schen. Zwingende gesetzliche Bestimmungen \u2013 insb. Aufbewahrungsfristen \u2013 bleiben unber\u00FChrt.</p>'
+ '<p>Auf die Speicherdauer Ihrer Daten, die von den Betreibern der sozialen Netzwerke zu eigenen Zwecken gespeichert werden, haben wir keinen Einfluss. F\u00FCr Einzelheiten dazu informieren Sie sich bitte direkt bei den Betreibern der sozialen Netzwerke (z. B. in deren Datenschutzerkl\u00E4rung, siehe unten).</p>'

+ '<p><strong>Soziale Netzwerke im Einzelnen</strong></p>'
+ '<p><strong>Facebook</strong></p>'
+ '<p>Wir verf\u00FCgen \u00FCber ein Profil bei Facebook. Anbieter dieses Dienstes ist die Facebook Ireland Limited, 4 Grand Canal Square, Grand Canal Harbour, Dublin 2, Irland. Die erfassten Daten werden nach Aussage von Facebook auch in die USA und in andere Drittl\u00E4nder \u00FCbertragen.</p>'
+ '<p>Wir haben mit Facebook eine Vereinbarung \u00FCber gemeinsame Verarbeitung (Controller Addendum) geschlossen. In dieser Vereinbarung wird festgelegt, f\u00FCr welche Datenverarbeitungsvorg\u00E4nge wir bzw. Facebook verantwortlich ist, wenn Sie unsere Facebook-Page besuchen. Diese Vereinbarung k\u00F6nnen Sie unter folgendem Link einsehen: <a href="https://www.facebook.com/legal/terms/page_controller_addendum" target="_blank" rel="noopener">https://www.facebook.com/legal/terms/page_controller_addendum</a>.</p>'
+ '<p>Sie k\u00F6nnen Ihre Werbeeinstellungen selbstst\u00E4ndig in Ihrem Nutzer-Account anpassen. Klicken Sie hierzu auf folgenden Link und loggen Sie sich ein: <a href="https://www.facebook.com/settings?tab=ads" target="_blank" rel="noopener">https://www.facebook.com/settings?tab=ads</a>.</p>'
+ '<p>Details entnehmen Sie der Datenschutzerkl\u00E4rung von Facebook: <a href="https://www.facebook.com/about/privacy/" target="_blank" rel="noopener">https://www.facebook.com/about/privacy/</a>.</p>'

+ '<p><strong>Instagram</strong></p>'
+ '<p>Wir verf\u00FCgen \u00FCber ein Profil bei Instagram. Anbieter ist die Instagram Inc., 1601 Willow Road, Menlo Park, CA, 94025, USA. Details zu deren Umgang mit Ihren personenbezogenen Daten entnehmen Sie der Datenschutzerkl\u00E4rung von Instagram: <a href="https://help.instagram.com/519522125107875" target="_blank" rel="noopener">https://help.instagram.com/519522125107875</a>.</p>'

+ '<p><strong>YouTube</strong></p>'
+ '<p>Wir verf\u00FCgen \u00FCber ein Profil bei YouTube. Anbieter ist die Google Ireland Limited, Gordon House, Barrow Street, Dublin 4, Irland. Details zu deren Umgang mit Ihren personenbezogenen Daten entnehmen Sie der Datenschutzerkl\u00E4rung von YouTube: <a href="https://policies.google.com/privacy?hl=de" target="_blank" rel="noopener">https://policies.google.com/privacy?hl=de</a>.</p>';
