/* ════════════════════════════════════════════════════════════════
   IMPRESSUM und DATENSCHUTZERKLÄRUNG
   Texte 1:1 aus offiziellem Auftraggeber-Material übernommen
   ════════════════════════════════════════════════════════════════ */

window._IMPRESSUM_HTML =
'<h3>Impressum</h3>'
+ '<p><strong>GEMEINSCHAFTSINITIATIVE \u201CWIR WESTERW\u00C4LDER\u201D</strong><br>'
+ 'Aktiv zwischen Rhein und Sieg</p>'
+ '<p>Wir Westerw\u00E4lder gA\u00F6R<br>'
+ 'K\u00F6nigsberger Str. 40<br>'
+ '56269 Dierdorf</p>'

+ '<h3>Kontakt</h3>'
+ '<p>Telefon: 02689 95929-40<br>'
+ 'Telefax: 02689 95929-49<br>'
+ 'E-Mail: <a href="mailto:info@wir-westerwaelder.de">info@wir-westerwaelder.de</a></p>'

+ '<p>Vorstand: Sandra K\u00F6ster<br>'
+ 'Vorsitzender des Verwaltungsrates: Landrat Achim Hallerbach</p>'

+ '<p>Die Gemeinschaftsinitiative \u201CWir Westerw\u00E4lder\u201D wird getragen durch die Landkreise Altenkirchen, Neuwied und Westerwaldkreis. Die Landkreise sind K\u00F6rperschaften des \u00F6ffentlichen Rechts. Sie werden durch den jeweiligen Landrat vertreten.</p>'

+ '<p><strong>Kreisverwaltung Altenkirchen</strong><br>'
+ 'Vertreten durch:<br>'
+ 'Landrat Dr. Peter Enders<br>'
+ 'Parkstra\u00DFe 1<br>'
+ '57610 Altenkirchen<br>'
+ 'Telefon: 02681 81-0<br>'
+ 'Telefax: 02681 81-2000<br>'
+ 'E-Mail: <a href="mailto:post@kreis-ak.de">post@kreis-ak.de</a></p>'

+ '<p><strong>Kreisverwaltung Neuwied</strong><br>'
+ 'Vertreten durch:<br>'
+ 'Landrat Achim Hallerbach<br>'
+ 'Wilhelm-Leuschner-Stra\u00DFe 9<br>'
+ 'D-56564 Neuwied<br>'
+ 'Telefon: 02631 803-0 (Zentrale)<br>'
+ 'Telefax: 02631 803-93-222<br>'
+ 'E-Mail: <a href="mailto:poststelle@kreis-neuwied.de">poststelle@kreis-neuwied.de</a></p>'

+ '<p><strong>Kreisverwaltung des Westerwaldkreises</strong><br>'
+ 'Vertreten durch:<br>'
+ 'Landrat Achim Schwickert<br>'
+ 'Peter-Altmeier-Platz 1<br>'
+ '56410 Montabaur<br>'
+ 'Telefon: 02602 124-0<br>'
+ 'Telefax: 02602 124-238<br>'
+ 'E-Mail: <a href="mailto:kreisverwaltung@westerwaldkreis.de">kreisverwaltung@westerwaldkreis.de</a></p>'

+ '<h3>Inhaltliche Verantwortung</h3>'
+ '<p>Sandra K\u00F6ster<br>'
+ 'Wir Westerw\u00E4lder gA\u00F6R<br>'
+ 'K\u00F6nigsberger Stra\u00DFe 40, 56269 Dierdorf<br>'
+ 'Telefon 02689-95929-40</p>'

+ '<h3>Konzeption, Design, Entwicklung &amp; Programmierung</h3>'
+ '<p>PAGE &amp; PAPER \u2013 Agentur f\u00FCr Kommunikation GmbH &amp; Co. KG<br>'
+ 'Barrwiese 3<br>'
+ '57627 Hachenburg</p>'

+ '<p><strong>Weitere Kan\u00E4le der Wir Westerw\u00E4lder gA\u00F6R</strong></p>'
+ '<ul>'
+ '<li>Website: <a href="https://www.wir-westerwaelder.de" target="_blank" rel="noopener">www.wir-westerwaelder.de</a></li>'
+ '<li>Spotify</li>'
+ '<li>Apple Podcast</li>'
+ '<li>LinkedIn</li>'
+ '<li>YouTube</li>'
+ '<li>Instagram</li>'
+ '<li>Facebook</li>'
+ '</ul>'

+ '<h3>Bildnachweis</h3>'
+ '<p>Dominik Ketz Fotografie, <a href="https://www.dominikketz.de" target="_blank" rel="noopener">www.dominikketz.de</a><br>'
+ 'Matthias Ketz Photographie, <a href="https://www.foto-ketz.de" target="_blank" rel="noopener">www.foto-ketz.de</a><br>'
+ 'Martin Fandler, foto-fandler.de<br>'
+ 'Tourist-Information Montabaur, kmaas@montabaur.de<br>'
+ 'Tourist-Information Rengsdorf, tourist@rengsdorf.de<br>'
+ 'Hotel Heinz GmbH, info@hotel-heinz.de<br>'
+ 'Rheinland-Pfalz Tourismus GmbH, info@gastlandschaften.de<br>'
+ 'J\u00F6rg Hohenadl; Naturgenuss Rhein-Westerwald, <a href="https://www.naturgenuss-partner.de" target="_blank" rel="noopener">www.naturgenuss-partner.de</a><br>'
+ 'Regionale Partner aus dem Einkaufsf\u00FChrer Westerwald</p>'

+ '<h3>Bildnachweise</h3>'
+ '<p>Die folgenden Bilder wurden verwendet und stammen von den genannten Quellen:</p>'
+ '<p><strong>Adobe Stock</strong></p>'
+ '<ul>'
+ '<li>AdobeStock_144420188.ai</li>'
+ '<li>AdobeStock_244784231.jpeg</li>'
+ '<li>AdobeStock_352139863.jpeg</li>'
+ '<li>AdobeStock_354792162.jpeg</li>'
+ '<li>AdobeStock_397095086.ai</li>'
+ '<li>AdobeStock_442937999.jpeg</li>'
+ '<li>AdobeStock_553143458.ai</li>'
+ '<li>AdobeStock_576871114.ai</li>'
+ '<li>AdobeStock_576871114.jpeg</li>'
+ '<li>AdobeStock_807136369.jpeg</li>'
+ '<li>AdobeStock_825087493.jpeg</li>'
+ '<li>AdobeStock_890986439.jpeg</li>'
+ '<li>AdobeStock_1007148027.jpeg</li>'
+ '<li>AdobeStock_1012018936.jpeg</li>'
+ '<li>AdobeStock_1024593601.jpeg</li>'
+ '<li>AdobeStock_1037823821.jpeg</li>'
+ '<li>AdobeStock_1070253592.jpeg</li>'
+ '<li>AdobeStock_1088483877.jpeg</li>'
+ '<li>AdobeStock_1136711510.jpeg</li>'
+ '<li>AdobeStock_1200051178.jpeg</li>'
+ '<li>AdobeStock_1233686142.jpeg</li>'
+ '<li>AdobeStock_1251914079.jpeg</li>'
+ '</ul>'
+ '<p><strong>iStock</strong></p>'
+ '<ul>'
+ '<li>iStock-683962670.jpg</li>'
+ '<li>iStock-1159783574.eps</li>'
+ '<li>iStock-1176632037.jpg</li>'
+ '<li>iStock-1316989941.eps</li>'
+ '<li>iStock-1318686980.eps</li>'
+ '<li>iStock-2174600729.jpg</li>'
+ '<li>iStock-2191560255.jpg</li>'
+ '</ul>'
+ '<p>Martina Haas, <a href="https://www.haas-ideen.com" target="_blank" rel="noopener">www.haas-ideen.com</a></p>'

+ '<h3>HAFTUNGSAUSSCHLUSS (DISCLAIMER)</h3>'
+ '<p><strong>HAFTUNG F\u00DCR INHALTE</strong></p>'
+ '<p>Als Diensteanbieter sind wir gem\u00E4\u00DF \u00A7 7 Abs.1 TMG f\u00FCr eigene Inhalte auf diesen Seiten nach den allgemeinen Gesetzen verantwortlich. Nach \u00A7\u00A7 8 bis 10 TMG sind wir als Diensteanbieter jedoch nicht verpflichtet, \u00FCbermittelte oder gespeicherte fremde Informationen zu \u00FCberwachen oder nach Umst\u00E4nden zu forschen, die auf eine rechtswidrige T\u00E4tigkeit hinweisen. Verpflichtungen zur Entfernung oder Sperrung der Nutzung von Informationen nach den allgemeinen Gesetzen bleiben hiervon unber\u00FChrt. Eine diesbez\u00FCgliche Haftung ist jedoch erst ab dem Zeitpunkt der Kenntnis einer konkreten Rechtsverletzung m\u00F6glich. Bei Bekanntwerden von entsprechenden Rechtsverletzungen werden wir diese Inhalte umgehend entfernen.</p>'

+ '<p><strong>HAFTUNG F\u00DCR LINKS</strong></p>'
+ '<p>Unser Angebot enth\u00E4lt Links zu externen Webseiten Dritter, auf deren Inhalte wir keinen Einfluss haben. Deshalb k\u00F6nnen wir f\u00FCr diese fremden Inhalte auch keine Gew\u00E4hr \u00FCbernehmen. F\u00FCr die Inhalte der verlinkten Seiten ist stets der jeweilige Anbieter oder Betreiber der Seiten verantwortlich. Die verlinkten Seiten wurden zum Zeitpunkt der Verlinkung auf m\u00F6gliche Rechtsverst\u00F6\u00DFe \u00FCberpr\u00FCft. Rechtswidrige Inhalte waren zum Zeitpunkt der Verlinkung nicht erkennbar. Eine permanente inhaltliche Kontrolle der verlinkten Seiten ist jedoch ohne konkrete Anhaltspunkte einer Rechtsverletzung nicht zumutbar. Bei Bekanntwerden von Rechtsverletzungen werden wir derartige Links umgehend entfernen.</p>'

+ '<p><strong>URHEBERRECHT</strong></p>'
+ '<p>Die durch die Seitenbetreiber erstellten Inhalte und Werke auf diesen Seiten unterliegen dem deutschen Urheberrecht. Die Vervielf\u00E4ltigung, Bearbeitung, Verbreitung und jede Art der Verwertung au\u00DFerhalb der Grenzen des Urheberrechtes bed\u00FCrfen der schriftlichen Zustimmung des jeweiligen Autors bzw. Erstellers. Downloads und Kopien dieser Seite sind nur f\u00FCr den privaten, nicht kommerziellen Gebrauch gestattet. Soweit die Inhalte auf dieser Seite nicht vom Betreiber erstellt wurden, werden die Urheberrechte Dritter beachtet. Insbesondere werden Inhalte Dritter als solche gekennzeichnet. Sollten Sie trotzdem auf eine Urheberrechtsverletzung aufmerksam werden, bitten wir um einen entsprechenden Hinweis. Bei Bekanntwerden von Rechtsverletzungen werden wir derartige Inhalte umgehend entfernen.</p>'

+ '<h3>EU-Streitschlichtung</h3>'
+ '<p>Die Europ\u00E4ische Kommission stellt eine Plattform zur Online-Streitbeilegung (OS) bereit: '
+ '<a href="https://ec.europa.eu/consumers/odr/" target="_blank" rel="noopener">https://ec.europa.eu/consumers/odr/</a>.<br>'
+ 'Unsere E-Mail-Adresse finden Sie oben im Impressum.</p>'

+ '<h3>Verbraucherstreitbeilegung / Universalschlichtungsstelle</h3>'
+ '<p>Wir sind nicht bereit oder verpflichtet, an Streitbeilegungsverfahren vor einer Verbraucherschlichtungsstelle teilzunehmen.</p>';


window._DATENSCHUTZ_HTML =
'<h3>Datenschutzerklärung</h3>'
+ '<p><em>Stand: Mai 2026</em></p>'
+ '<p>Diese Datenschutzerklärung beschreibt, wie diese App – die mobile Web-App <strong>„Guck ma, Westerwald"</strong> – mit personenbezogenen Daten umgeht. Die App ist absichtlich datenschutzfreundlich gestaltet und erhebt selbst keine personenbezogenen Daten.</p>'

+ '<h3>1. Verantwortliche Stelle</h3>'
+ '<p>Verantwortlich für die Datenverarbeitung im Sinne der Datenschutz-Grundverordnung (DSGVO) ist:</p>'
+ '<p><strong>Wir Westerwälder gAöR</strong><br>'
+ 'Königsberger Straße 40<br>'
+ '56269 Dierdorf<br>'
+ 'Telefon: 02689 95929-40<br>'
+ 'Telefax: 02689 95929-49<br>'
+ 'E-Mail: <a href="mailto:info@wir-westerwaelder.de">info@wir-westerwaelder.de</a><br>'
+ 'Website: <a href="https://www.wir-westerwaelder.de" target="_blank" rel="noopener">www.wir-westerwaelder.de</a></p>'
+ '<p>Vorstand: Sandra Köster<br>'
+ 'Vorsitzender des Verwaltungsrates: Landrat Achim Hallerbach</p>'

+ '<h3>2. Datenschutzbeauftragte</h3>'
+ '<p>Bei datenschutzrechtlichen Fragen können Sie sich an die Datenschutzbeauftragten der Trägerlandkreise wenden:</p>'
+ '<p><strong>Behördlicher Datenschutzbeauftragter Landkreis Altenkirchen:</strong><br>'
+ 'Parkstraße 1, 57610 Altenkirchen<br>'
+ 'Telefon: 02681 81-3636<br>'
+ 'E-Mail: <a href="mailto:datenschutz@kreis-ak.de">datenschutz@kreis-ak.de</a></p>'
+ '<p><strong>Behördlicher Datenschutzbeauftragter Kreisverwaltung Neuwied:</strong><br>'
+ 'Christian Fuß, Wilhelm-Leuschner-Straße 9, 56564 Neuwied<br>'
+ 'Telefon: 02631 803-435<br>'
+ 'E-Mail: <a href="mailto:Christian.Fuss@kreis-neuwied.de">Christian.Fuss@kreis-neuwied.de</a></p>'
+ '<p><strong>Behördliche Datenschutzbeauftragte Westerwaldkreis:</strong><br>'
+ 'Sabine Schulz-Lauth<br>'
+ 'Telefon: 02602 124-792<br>'
+ 'E-Mail: <a href="mailto:Sabine.Schulz-Lauth@westerwaldkreis.de">Sabine.Schulz-Lauth@westerwaldkreis.de</a></p>'

+ '<h3>3. Umfang der Datenverarbeitung</h3>'
+ '<p>Diese App ist eine reine Informations-App. Sie wird als statische Web-Anwendung über GitHub Pages ausgeliefert.</p>'
+ '<p><strong>Wir selbst erheben und speichern KEINE personenbezogenen Daten.</strong> Insbesondere:</p>'
+ '<ul>'
+ '<li>Es werden <strong>keine Cookies</strong> auf Ihrem Endgerät gesetzt.</li>'
+ '<li>Es werden <strong>keine Daten in den lokalen Speicher (LocalStorage / SessionStorage)</strong> Ihres Geräts geschrieben.</li>'
+ '<li>Es findet <strong>kein Tracking, kein Profiling, keine Reichweitenmessung</strong> statt.</li>'
+ '<li>Es werden <strong>keine Analyse-Tools</strong> (z. B. Google Analytics, Matomo) eingesetzt.</li>'
+ '<li>Es gibt <strong>kein Nutzerkonto, kein Kontaktformular, keinen Newsletter</strong> innerhalb dieser App.</li>'
+ '<li>Die Datenschutz-Akzeptanz wird bei jedem Aufruf der App neu abgefragt und nicht gespeichert.</li>'
+ '</ul>'

+ '<h3>4. Hosting durch GitHub Pages</h3>'
+ '<p>Die App wird über den Dienst GitHub Pages der GitHub Inc., 88 Colin P Kelly Jr St, San Francisco, CA 94107, USA, ausgeliefert.</p>'
+ '<p>Bei jedem Aufruf der App werden technisch zwingend folgende Daten an die Server von GitHub übertragen und in <strong>Server-Log-Dateien</strong> gespeichert:</p>'
+ '<ul>'
+ '<li>IP-Adresse des aufrufenden Geräts</li>'
+ '<li>Datum und Uhrzeit der Anfrage</li>'
+ '<li>Aufgerufene Datei</li>'
+ '<li>User-Agent (Browser-Kennung) und Referrer</li>'
+ '</ul>'
+ '<p>Diese Verarbeitung erfolgt durch GitHub Inc. auf Grundlage des berechtigten Interesses gemäß Art. 6 Abs. 1 lit. f DSGVO an einer technisch stabilen und sicheren Auslieferung der App.</p>'
+ '<p>GitHub kann Daten in die USA übertragen. Rechtsgrundlage hierfür sind die Standardvertragsklauseln der EU-Kommission. Weitere Informationen finden Sie in der Datenschutzerklärung von GitHub: <a href="https://docs.github.com/en/site-policy/privacy-policies/github-general-privacy-statement" target="_blank" rel="noopener">https://docs.github.com/en/site-policy/privacy-policies/github-general-privacy-statement</a></p>'

+ '<h3>5. Externe Inhalte (eingebettete Dienste Dritter)</h3>'
+ '<p>Diese App bindet zur Anzeige von Inhalten externe Dienste Dritter ein. Beim Aufruf dieser Inhalte wird Ihre IP-Adresse direkt an den jeweiligen Anbieter übertragen. Sie haben jeweils die Möglichkeit, den Inhalt nicht zu nutzen oder die App zu schließen.</p>'

+ '<p><strong>5.1 Logos und Bilder von wir-westerwaelder.de</strong></p>'
+ '<p>In der Rubrik „Westerwald-Box" werden Logos und Beispielbilder direkt von <a href="https://wir-westerwaelder.de" target="_blank" rel="noopener">wir-westerwaelder.de</a> geladen. Anbieter ist die Wir Westerwälder gAöR (siehe Verantwortliche Stelle). Da Anbieter und verantwortliche Stelle identisch sind, findet hier keine Datenweitergabe an Dritte statt.</p>'

+ '<p><strong>5.2 Westerwald Touristik-Service (westerwald.info)</strong></p>'
+ '<p>In den Rubriken „Unterkünfte" und „Ausflugsziele" werden Live-Daten in einem iFrame von <a href="https://www.westerwald.info" target="_blank" rel="noopener">www.westerwald.info</a> eingebettet. Anbieter ist der Westerwald Touristik-Service e.V., Kirchstraße 48a, 56410 Montabaur. Beim Aufruf werden u. a. IP-Adresse und Browser-Kennung an deren Server übertragen.</p>'
+ '<p>Datenschutzerklärung des Anbieters: <a href="https://www.westerwald.info/datenschutz/" target="_blank" rel="noopener">https://www.westerwald.info/datenschutz/</a></p>'

+ '<p><strong>5.3 ÖPNV-Anbieter (Bahn & Bus)</strong></p>'
+ '<p>In der Rubrik „Bahn & Bus" werden in einem iFrame folgende Webseiten eingebettet:</p>'
+ '<ul>'
+ '<li>Westerwaldbus GmbH, <a href="https://www.westerwaldbus.de" target="_blank" rel="noopener">www.westerwaldbus.de</a></li>'
+ '<li>Westerwaldkreis (ÖPNV), <a href="https://www.westerwaldkreis.de" target="_blank" rel="noopener">www.westerwaldkreis.de</a></li>'
+ '<li>Verkehrsverbund Rhein-Mosel (VRM), <a href="https://www.vrminfo.de" target="_blank" rel="noopener">www.vrminfo.de</a></li>'
+ '</ul>'
+ '<p>Beim Öffnen dieser Inhalte werden Ihre IP-Adresse und Browser-Kennung an die jeweiligen Anbieter übertragen. Bitte beachten Sie deren Datenschutzerklärungen.</p>'

+ '<p><strong>5.4 Google Docs Viewer (PDF-Anzeige auf Desktop)</strong></p>'
+ '<p>Auf Desktop-Browsern werden eingebettete PDF-Dokumente (z. B. Einkaufsführer, Naturgenuss-Broschüre) über den Google Docs Viewer (<code>https://docs.google.com/viewer</code>) angezeigt. Hierdurch werden Ihre IP-Adresse und die URL des aufgerufenen PDF an die Google LLC, 1600 Amphitheatre Parkway, Mountain View, CA 94043, USA übertragen.</p>'
+ '<p>Auf Smartphones wird der Google Docs Viewer nicht verwendet; PDFs öffnen sich dort über Ihren Browser oder System-Viewer.</p>'
+ '<p>Datenschutzerklärung von Google: <a href="https://policies.google.com/privacy" target="_blank" rel="noopener">https://policies.google.com/privacy</a></p>'

+ '<p><strong>5.5 Externe Links</strong></p>'
+ '<p>Die App enthält an verschiedenen Stellen Links zu externen Webseiten. Beim Anklicken solcher Links verlassen Sie diese App; ab diesem Zeitpunkt gelten die Datenschutzbestimmungen des jeweiligen Anbieters. Wir haben keinen Einfluss auf die Datenverarbeitung durch diese Anbieter.</p>'

+ '<h3>6. Rechtsgrundlagen der Datenverarbeitung</h3>'
+ '<p>Soweit im Rahmen der Bereitstellung dieser App eine technisch zwingende Datenverarbeitung erfolgt (z. B. durch GitHub Pages), beruht diese auf unserem berechtigten Interesse an der technisch fehlerfreien Bereitstellung der App gemäß Art. 6 Abs. 1 lit. f DSGVO.</p>'
+ '<p>Die Anzeige eingebundener externer Inhalte (siehe Ziffer 5) erfolgt erst, nachdem Sie die jeweilige Funktion der App aufrufen, und damit auf Grundlage Ihrer Einwilligung gemäß Art. 6 Abs. 1 lit. a DSGVO.</p>'

+ '<h3>7. Speicherdauer</h3>'
+ '<p>Wir selbst speichern keine personenbezogenen Daten. Die Speicherdauer der Server-Log-Daten bei GitHub Pages bzw. den eingebundenen Drittanbietern ergibt sich aus deren jeweiligen Datenschutzerklärungen.</p>'

+ '<h3>8. Ihre Rechte als betroffene Person</h3>'
+ '<p>Sie haben gegenüber der verantwortlichen Stelle folgende Rechte hinsichtlich der Sie betreffenden personenbezogenen Daten:</p>'
+ '<ul>'
+ '<li><strong>Auskunftsrecht</strong> (Art. 15 DSGVO)</li>'
+ '<li><strong>Recht auf Berichtigung</strong> (Art. 16 DSGVO)</li>'
+ '<li><strong>Recht auf Löschung</strong> (Art. 17 DSGVO)</li>'
+ '<li><strong>Recht auf Einschränkung der Verarbeitung</strong> (Art. 18 DSGVO)</li>'
+ '<li><strong>Recht auf Datenübertragbarkeit</strong> (Art. 20 DSGVO)</li>'
+ '<li><strong>Widerspruchsrecht</strong> (Art. 21 DSGVO)</li>'
+ '<li><strong>Recht auf Widerruf einer einmal erteilten Einwilligung</strong> mit Wirkung für die Zukunft (Art. 7 Abs. 3 DSGVO)</li>'
+ '</ul>'
+ '<p>Zur Ausübung dieser Rechte wenden Sie sich bitte an die unter Ziffer 1 genannte verantwortliche Stelle.</p>'

+ '<h3>9. Beschwerderecht bei der Aufsichtsbehörde</h3>'
+ '<p>Sie haben außerdem das Recht, sich mit einer Beschwerde an eine Datenschutz-Aufsichtsbehörde zu wenden, insbesondere im Mitgliedstaat Ihres gewöhnlichen Aufenthaltsorts, Ihres Arbeitsplatzes oder des Orts des mutmaßlichen Verstoßes.</p>'
+ '<p>Zuständige Aufsichtsbehörde für die verantwortliche Stelle:</p>'
+ '<p><strong>Der Landesbeauftragte für den Datenschutz und die Informationsfreiheit Rheinland-Pfalz</strong><br>'
+ 'Hintere Bleiche 34<br>'
+ '55116 Mainz<br>'
+ 'Telefon: 06131 8920-0<br>'
+ 'E-Mail: <a href="mailto:poststelle@datenschutz.rlp.de">poststelle@datenschutz.rlp.de</a><br>'
+ 'Website: <a href="https://www.datenschutz.rlp.de" target="_blank" rel="noopener">www.datenschutz.rlp.de</a></p>'

+ '<h3>10. SSL/TLS-Verschlüsselung</h3>'
+ '<p>Diese App wird ausschließlich verschlüsselt über HTTPS ausgeliefert. Eine verschlüsselte Verbindung erkennen Sie am „https://" in der Adresszeile Ihres Browsers sowie am Schloss-Symbol.</p>'

+ '<h3>11. Aktualität und Änderung dieser Datenschutzerklärung</h3>'
+ '<p>Diese Datenschutzerklärung hat den Stand Mai 2026. Durch die Weiterentwicklung der App oder geänderte gesetzliche bzw. behördliche Vorgaben kann es notwendig werden, diese Datenschutzerklärung anzupassen. Die jeweils aktuelle Version ist in dieser App über den Footer-Link „Datenschutz" abrufbar.</p>';
